import { StyleSheet, StatusBar } from 'react-native';

export const C = {
  bg: '#0A0A0C',
  panel: '#141419',
  panel2: '#1C1C24',
  border: '#222',
  verde: '#00FFCC',
  azul: '#00B8FF',
  texto: '#FFF',
  tenue: '#666',
  oscuro: '#121212'
};

export const st = StyleSheet.create({
  container: { flex: 1, backgroundColor: C.bg },
  centerView: { flex: 1, justifyContent: 'center', padding: 30, alignItems: 'center' },
  mainLogo: { color: '#FFF', fontSize: 38, fontWeight: '900', letterSpacing: 1, textShadowColor: C.verde, textShadowRadius: 12 },
  subLogo: { color: '#555', fontSize: 13, textAlign: 'center', marginTop: 5 },
  label: { color: C.verde, fontSize: 10, fontWeight: 'bold', marginBottom: 5, letterSpacing: 1 },
  input: { backgroundColor: C.panel, color: '#FFF', padding: 14, borderRadius: 10, borderWidth: 1, borderColor: C.border, marginBottom: 15, fontSize: 15 },
  neonBtn: { backgroundColor: C.verde, padding: 16, borderRadius: 10, alignItems: 'center', marginTop: 10, width: '100%' },
  neonBtnAlt: { backgroundColor: C.azul, padding: 16, borderRadius: 10, alignItems: 'center', marginTop: 10, width: '100%' },
  neonBtnTxt: { color: C.oscuro, fontWeight: '900', letterSpacing: 0.5 },
  headerTitle: { color: '#FFF', fontSize: 24, fontWeight: '900' },
  card: { flexDirection: 'row', backgroundColor: C.panel, padding: 18, borderRadius: 14, marginBottom: 12, alignItems: 'center', borderWidth: 1, borderColor: C.border },
  cardLocked: { opacity: 0.45 },
  cardTitle: { color: '#FFF', fontSize: 16, fontWeight: 'bold' },
  miniBtn: { backgroundColor: C.verde, paddingVertical: 8, paddingHorizontal: 14, borderRadius: 8 },
  miniBtnOff: { backgroundColor: '#333', paddingVertical: 8, paddingHorizontal: 14, borderRadius: 8 },
  fab: { position: 'absolute', bottom: 25, right: 25, backgroundColor: C.verde, width: 56, height: 56, borderRadius: 28, justifyContent: 'center', alignItems: 'center', elevation: 5 },
  overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.85)', justifyContent: 'center', padding: 25 },
  modalBox: { backgroundColor: C.panel, borderRadius: 16, padding: 25, borderWidth: 1, borderColor: '#333' },
  modalTitle: { color: C.verde, fontSize: 14, fontWeight: '900', textAlign: 'center', marginBottom: 15 },
  topBar: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 15, paddingBottom: 12, paddingTop: (StatusBar.currentHeight || 30) + 10, backgroundColor: C.panel },
  voiceBanner: { backgroundColor: C.verde, paddingVertical: 5, alignItems: 'center' },
  voiceBannerText: { color: C.oscuro, fontSize: 9, fontWeight: '900' },
  tabBar: { flexDirection: 'row', height: 60, backgroundColor: C.panel, borderTopWidth: 1, borderTopColor: C.border },
  tabItem: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  bubble: { padding: 10, borderRadius: 12, marginBottom: 8, maxWidth: '80%' },
  bubbleYo: { backgroundColor: C.panel, alignSelf: 'flex-end', borderWidth: 1, borderColor: C.verde },
  bubbleAmigo: { backgroundColor: C.panel2, alignSelf: 'flex-start', borderWidth: 1, borderColor: C.border },
  inputBar: { flexDirection: 'row', padding: 10, backgroundColor: C.panel, alignItems: 'center' },
  sendBtn: { backgroundColor: C.verde, width: 40, height: 40, borderRadius: 20, justifyContent: 'center', alignItems: 'center', marginLeft: 8 },
  musicBox: { backgroundColor: C.panel, padding: 15, borderRadius: 12, borderWidth: 1, borderColor: C.verde, marginBottom: 15 },
  ctrlRow: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', marginTop: 12 },
  ctrlBtn: { backgroundColor: C.panel2, borderWidth: 1, borderColor: C.azul, width: 52, height: 52, borderRadius: 26, justifyContent: 'center', alignItems: 'center', marginHorizontal: 8 },
  playBtn: { backgroundColor: C.verde, width: 64, height: 64, borderRadius: 32, justifyContent: 'center', alignItems: 'center', marginHorizontal: 8 },
  smallCard: { flexDirection: 'row', backgroundColor: C.panel, padding: 12, borderRadius: 8, marginBottom: 6, alignItems: 'center' },
  box: { backgroundColor: C.panel, padding: 15, borderRadius: 12, marginBottom: 15 },
  imcCard: { backgroundColor: C.verde, padding: 15, borderRadius: 10, alignItems: 'center', marginTop: 15 },
  switchRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginVertical: 10 },
  avatarRow: { flexDirection: 'row', paddingHorizontal: 12, paddingVertical: 10, backgroundColor: C.panel, borderBottomWidth: 1, borderBottomColor: C.border },
  avatar: { width: 38, height: 38, borderRadius: 19, borderWidth: 2, borderColor: C.verde, backgroundColor: C.panel2, justifyContent: 'center', alignItems: 'center', marginRight: 10 },
  avatarTxt: { color: C.verde, fontWeight: '900' },
  sectionTitle: { color: C.azul, fontSize: 11, fontWeight: '900', letterSpacing: 1, marginBottom: 8, marginTop: 6 },
  calCell: { width: '14.285%', aspectRatio: 1, justifyContent: 'center', alignItems: 'center' },
  calDay: { width: 34, height: 34, borderRadius: 17, justifyContent: 'center', alignItems: 'center' }
});
